mapping_dict = {
    "diagnosis_primary": "2 Primary G",
    "diagnosis_secondary": "2 secondary G",
    "if_childbirth_d": "2.Date_of_birth_d G",
    "if_childbirth_m": "2.Date_of_birth_m G",
    "if_childbirth_y": "2.Date_of_birth_y G",
    "if_childbirth_method": "2 chidbirth G",
    "whether_occupational_illness": "2 Occ illness G",
    "start_period_d": "2.Date_of_birth_d 2 G",
    "start_period_m": "2.Date_of_birth_m 2 G",
    "start_period_y": "2.Date_of_birth_y 2 G",
    "has_hospitalized": "2 Has your patient G",
    "date_admitted_d": "2.Date_of_birth_d 4 G",
    "date_admitted_m": "2.Date_of_birth_m 4 G",
    "date_admitted_y": "2.Date_of_birth_y 4 G",
    "date_discharge_d": "2.Date_of_birth_d 5 G",
    "date_discharge_m": "2.Date_of_birth_m 5 G",
    "date_discharge_y": "2.Date_of_birth_m 5 G",
    "hospital_name": "2 Name of institution G",
    "had_surgery": "2 Has your patient 2 G",
    "surgery_d": "Date_of_birth_d 6 G",
    "surgery_m": "Date_of_birth_m 6 G",
    "surgery_y": "Date_of_birth_y 6 G",
    "surgery_description": "2 description G",
    "surgery_anaesthetic": "2 type of anaesthetic G",
    "treatment": "2 Treatment G",
    "prognosis": "2 prognosis G",
}
