mapping_dict = {
    "diagnosis_primary": "2 Primary G",
    "diagnosis_secondary": "2 secondary G",
    "if_childbirth_d": "2.Date_of_birth_d G",
    "if_childbirth_m": "2.Date_of_birth_m G",
    "if_childbirth_y": "2.Date_of_birth_y G",
    "if_childbirth_method": "2 chidbirth G",
    "whether_occupational_illness": "2 Occ illness G",
    "start_period_d": "2.Date_of_birth_d 2 G",
    "start_period_m": "2.Date_of_birth_m 2 G",
    "start_period_y": "2.Date_of_birth_y 2 G",
    "has_hospitalized": "2 Has your patient G",
    "date_admitted_d": "2.Date_of_birth_d 4 G",
    "date_admitted_m": "2.Date_of_birth_m 4 G",
    "date_admitted_y": "2.Date_of_birth_y 4 G",
    "date_discharge_d": "2.Date_of_birth_d 5 G",
    "date_discharge_m": "2.Date_of_birth_m 5 G",
    "date_discharge_y": "2.Date_of_birth_m 5 G",
    "hospital_name": "2 Name of institution G",
    "had_surgery": "2 Has your patient 2 G",
    "surgery_d": "Date_of_birth_d 6 G",
    "surgery_m": "Date_of_birth_m 6 G",
    "surgery_y": "Date_of_birth_y 6 G",
    "surgery_description": "2 description G",
    "surgery_anaesthetic": "2 type of anaesthetic G",
    "treatment": "2 Treatment G",
    "treatment_1": "2 Treatment 2 G",
    "prognosis": "2 prognosis G",
    "history": "3 History G",
    "prev_treatment_d": "Date_of_birth_d G",
    "prev_treatment_m": "Date_of_birth_m G",
    "prev_treatment_y": "Date_of_birth_y G",
    "visit_freq": "3 other G",
    "symptoms": "3 Symp G",
    "symptoms_1": "3 Symp 2 G",
    "symptoms_2": "3 Symp 3 G",
    "are_tests_investigation_pending": "3 Are tests G",
    "expected_dor_d": "Date_of_birth_d 2 G",
    "expected_dor_m": "Date_of_birth_m 2 G",
    "expected_dor_y": "Date_of_birth_y 2 G",
    "whether_consulted_specialist": "3 name of specialist G",
    "specialist_speciality": "3 Speciality G",
    "specialist_consultation_d": "Date_of_birth_d 3 G",
    "specialist_consultation_m": "Date_of_birth_m 3 G",
    "specialist_consultation_y": "Date_of_birth_y 3 G",
    "restrictions_and_limitations": "3 res G",
    "restrictions_and_limitations_1": "3 res 2 G",
    "restrictions_and_limitations_2": "3 res 3 G",
    "complications_and_other_conditions": "3 Comp G",
    "complications_and_other_conditions_1": "3 Comp 2 G",
    "complications_and_other_conditions_2": "3 Comp 3 G",
    "compliance_to_treatment": "3 Compliance to treat G",
    "competency": "3 Competency G",
}
